require_relative '../spec_helper'

module ArtDecomp describe Decomposer do
  let(:archs) { Object.new }
  let(:fsm)   { Object.new }
  let(:u)     { Object.new }
  let(:v)     { Object.new }
  let(:qu)    { Object.new }
  let(:qv)    { Object.new }
  let(:g)     { Object.new }
  let(:gens)  { {
    uv: [MiniTest::Mock.new.expect(:uv_pairs, [[fsm, u, v]], [fsm, archs])],
    qu: [MiniTest::Mock.new.expect(:blankets, [qu],          [fsm, u, v])],
    qv: [MiniTest::Mock.new.expect(:blankets, [[qv, g]],     [fsm, u, v, qu])],
  } }
  let(:decomposer) { Decomposer.new archs: archs, fsm: fsm, gens: gens }

  describe '#decompositions' do
    it 'yields the Decompositions generated by the generators' do
      decomposer.decompositions.must_include Decomposition.new fsm, u, v, qu, qv, g
      gens.values.each { |gs| gs.map(&:verify) }
    end
  end
end end
