Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  IgnoreCopDirectives: true
  Max: 87

Naming/FileName:
  Exclude:
    - art-decomp.gemspec
    - lib/art-decomp.rb

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - _
    - _v
    - a
    - b
    - g
    - qu
    - qv
    - u
    - v
    - v1
    - v2

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Not:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
