inherit_from: .rubocop_todo.yml

Style/EmptyCaseCondition:
  Enabled: false

Style/Not:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
