inherit_from: .rubocop_todo.yml

Layout/SpaceAroundOperators:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Not:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
